name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "0 */10 * * *"   # every 10 hours
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl app
        run: |
          curl -I --max-time 20 "https://gym-monster.streamlit.app/" || true
